# Generated by Django 4.1.2 on 2023-12-15 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_product_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="count",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="rate",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="product", name="image", field=models.URLField(),
        ),
    ]
