# Generated by Django 4.1.2 on 2023-12-15 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0006_product_count_product_rate_alter_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
